-- Sawtooth Land Surveying application database.
-- Run this script in Supabase SQL Editor after rotating any exposed service keys.

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  first_name text not null,
  middle_name text,
  last_name text not null,
  preferred_name text,
  email text not null,
  phone_country_code text,
  phone_number text not null,
  alternative_phone text,
  preferred_contact_method text,
  country_of_residence text not null,
  city text,
  region text,
  postal_code text,
  full_address text,
  current_job_title text,
  current_employer text,
  total_surveying_experience numeric,
  senior_surveying_experience numeric,
  field_surveying_experience numeric,
  office_surveying_experience numeric,
  survey_specializations jsonb not null default '[]'::jsonb,
  work_authorized text,
  requires_sponsorship text,
  willing_to_relocate text,
  available_start_date date,
  supervised_teams text,
  number_supervised integer,
  technology_skills jsonb not null default '[]'::jsonb,
  software_skills jsonb not null default '[]'::jsonb,
  technical_summary text,
  resume_text text,
  applicant_declaration boolean not null default false,
  declaration_name text not null,
  status text not null default 'submitted' check (status in ('submitted', 'under_review', 'shortlisted', 'interview', 'accepted', 'rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.education (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.applications(id) on delete cascade,
  qualification_level text,
  qualification_title text not null,
  field_of_study text,
  institution text not null,
  country text not null,
  city text,
  completion_year text,
  currently_studying boolean not null default false
);

create table if not exists public.professional_credentials (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.applications(id) on delete cascade,
  credential_type text,
  credential_title text not null,
  issuing_country text not null,
  issuing_region text,
  issuing_authority text,
  credential_number text,
  issue_date date,
  expiry_date date,
  credential_status text
);

create table if not exists public.employment_history (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.applications(id) on delete cascade,
  employer text not null,
  job_title text not null,
  country text,
  city text,
  region text,
  employment_type text,
  start_date date,
  end_date date,
  currently_employed boolean not null default false,
  responsibilities text,
  major_projects text
);

create table if not exists public.project_experience (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.applications(id) on delete cascade,
  project_name text,
  project_type text,
  country text,
  location text,
  applicant_role text,
  project_duration text,
  equipment_software text,
  project_description text
);

create table if not exists public.applicant_references (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.applications(id) on delete cascade,
  reference_name text not null,
  organization text,
  job_title text,
  relationship text,
  email text,
  phone text,
  country text,
  permission_to_contact boolean not null default false
);

create table if not exists public.application_documents (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.applications(id) on delete cascade,
  document_type text not null,
  original_filename text not null,
  storage_path text not null,
  mime_type text,
  file_size bigint,
  uploaded_at timestamptz not null default now()
);

create index if not exists applications_created_at_idx on public.applications (created_at desc);
create index if not exists education_application_id_idx on public.education (application_id);
create index if not exists credentials_application_id_idx on public.professional_credentials (application_id);
create index if not exists employment_application_id_idx on public.employment_history (application_id);
create index if not exists projects_application_id_idx on public.project_experience (application_id);
create index if not exists references_application_id_idx on public.applicant_references (application_id);
create index if not exists documents_application_id_idx on public.application_documents (application_id);

alter table public.applications enable row level security;
alter table public.education enable row level security;
alter table public.professional_credentials enable row level security;
alter table public.employment_history enable row level security;
alter table public.project_experience enable row level security;
alter table public.applicant_references enable row level security;
alter table public.application_documents enable row level security;

insert into storage.buckets (id, name, public)
values ('application-documents', 'application-documents', false)
on conflict (id) do update set public = excluded.public;